{% set name = "cmec_driver" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmecmetrics/cmec-driver/archive/refs/tags/{{ version }}.tar.gz
  sha256: 179d1dde8da9eedc5071e4ea6c7cce9a02278f9ed77a3a34ae2b15ab694066e0

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python
  entry_points:
    - cmec-driver = cmec_driver.cmec_driver:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - cmec_driver
  commands:
    - cmec-driver --help

about:
  home: https://github.com/cmecmetrics/cmec-driver
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Coordinated Model Evaluation Capabilities (CMEC) driver'
  description: |
    This driver is used for organizing evaluation modules on the local system.
  doc_url: https://github.com/cmecmetrics/cmec-driver/wiki
  dev_url: https://github.com/cmecmetrics/cmec-driver

extra:
  recipe-maintainers:
    - acordonez
    - paullric
    - xylar
