{% set name = "cmec_driver" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmecmetrics/cmec-driver/archive/refs/tags/{{ version }}.tar.gz
  sha256: abb477f7c43b6ffe9ead0456b4c56448f11a2093f5fae9590fd22beb81959f20

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python
  entry_points:
    - cmec-driver = cmec_driver:main

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - cmec_driver
  commands:
    - cmec-driver --help

about:
  home: https://github.com/cmecmetrics/cmec-driver
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Coordinated Model Evaluation Capabilities (CMEC) driver'
  description: |
    This driver is used for organizing evaluation modules on the local system.
  doc_url: https://github.com/cmecmetrics/cmec-driver/wiki
  dev_url: https://github.com/cmecmetrics/cmec-driver

extra:
  recipe-maintainers:
    - acordonez
    - paullric
    - xylar
